# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/survey/vote, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/survey/add, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/survey/userSurvey, roles: ROLE_USER }
        - { path: ^/survey/edit, roles: ROLE_USER }
        - { path: ^/survey/cancel, roles: ROLE_USER }
        - { path: ^/survey/resend, roles: ROLE_USER }
        - { path: ^/survey/react, roles: ROLE_ADMIN }
        - { path: ^/survey/cancelList, roles: ROLE_ADMIN }
        - { path: ^/survey, roles: ROLE_ADMIN }
        - { path: ^/rate, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/staffrate, roles: ROLE_ADMIN }
        - { path: ^/team, roles: ROLE_ADMIN }
        - { path: ^/users, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: ROLE_ADMIN }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }



