<?php

namespace SurveyBundle\Repository;

/**
 * SurveyResendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyResendRepository extends \Doctrine\ORM\EntityRepository
{
}
