<?php

namespace SurveyBundle\Repository;

/**
 * SurveyStaffRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyStaffRateRepository extends \Doctrine\ORM\EntityRepository
{
}
